spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 130350250523-6iorqmbgvnc20hjpll7iirb642qgmnbh.apps.googleusercontent.com
            clientSecret: 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
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube

logging:
  level:
    com.example.apka2: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE